Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -90,19 +90,24 @@ jobs:
             make
 
 
-      - name: Install MSYS2 (Windows x86)
+      - name: Pin MSYS2 CRT (Windows x86)
         if: matrix.runtime.name == 'win-x86'
-        uses: msys2/setup-msys2@v2
-        with:
-          msystem: MINGW32
-          update: false
-          install: >
-            mingw-w64-i686-toolchain
-            mingw-w64-i686-cmake
-            mingw-w64-i686-gcc
-            mingw-w64-i686-pkgconf
-            mingw-w64-i686-zlib
-            make
+        shell: msys2 {0}
+        run: |
+          set -euxo pipefail
+
+          # Temporary workaround for the MinGW32 CRT regression introduced after 2026-06-10.
+          # The newer i686 CRT pulls i386__beginthreadex.o from libmsvcrt.a, which currently
+          # fails to resolve __mingw_SEH_error_handler when building qpdf.dll with -static.
+          pacman --noconfirm -U \
+            https://repo.msys2.org/mingw/mingw32/mingw-w64-i686-headers-14.0.0.r92.g818fa6510-1-any.pkg.tar.zst \
+            https://repo.msys2.org/mingw/mingw32/mingw-w64-i686-crt-14.0.0.r92.g818fa6510-1-any.pkg.tar.zst
+
+          pacman -Q \
+            mingw-w64-i686-gcc \
+            mingw-w64-i686-binutils \
+            mingw-w64-i686-headers \
+            mingw-w64-i686-crt
 
 
       - name: Install MSYS2 (Windows arm64)
@@ -124,15 +129,7 @@ jobs:
         shell: msys2 {0}
         run: |
           cd qpdf
-
-          # required for win-x86 build
-          LINKER_FLAGS="-static -Wl,--gc-sections -s"
-          
-          if [ "${{ matrix.runtime.name }}" = "win-x86" ]; then
-            LINKER_FLAGS="$LINKER_FLAGS -Wl,-u,__mingw_SEH_error_handler"
-          fi
-
-          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DUSE_IMPLICIT_CRYPTO=OFF -DREQUIRE_CRYPTO_NATIVE=ON -DCMAKE_CXX_FLAGS="$QPDF_CXX_FLAGS" -DCMAKE_SHARED_LINKER_FLAGS="$LINKER_FLAGS"
+          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DUSE_IMPLICIT_CRYPTO=OFF -DREQUIRE_CRYPTO_NATIVE=ON -DCMAKE_CXX_FLAGS="$QPDF_CXX_FLAGS" -DCMAKE_SHARED_LINKER_FLAGS="-static -Wl,--gc-sections -s"
           cmake --build build --parallel --target libqpdf
 
 
